module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: 'USER_DETAIL',
    LEAD_ADD_NEW: 'LEAD_ADD_NEW',
    PROJECT_ADD_NEW: 'PROJECT_ADD_NEW',
    PROJECT_ADD_USER: 'PROJECT_ADD_USER',
    PROJECT_ADD_TICKET: 'PROJECT_ADD_TICKET',
    PROJECT_EDIT: 'PROJECT_EDIT',
    TICKET_EDIT: 'TICKET_EDIT',
    CONFIRMATION: 'CONFIRMATION',
    DEFAULT: '',
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: 'NOTIFICATION',
    CALENDAR_EVENTS: 'CALENDAR_EVENTS',
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: 'LEAD_DELETE',
    PROJECT_DELETE: 'PROJECT_DELETE',
    TICKET_DELETE: 'TICKET_DELETE',
  },
});
